name: Replicar PR para Produção

on:
  pull_request_review:
    types: [submitted]

jobs:
  replicar-para-prod:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório de QA
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Pega o histórico completo
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Adicionar repositório de produção como remoto
        run: git remote add prod https://x-access-token:${{ secrets.API_TOKEN_GITHUB }}@github.com/brunolopesdev/nuxt-crud.git

      - name: Push da branch para produção
        run: |
          git push prod ${{ github.event.pull_request.head.ref }}:${{ github.event.pull_request.head.ref }}

      - name: Criar Pull Request no repositório de produção
        run: |
          gh pr create \
            --repo brunolopesdev/nuxt-crud \
            --head ${{ github.event.pull_request.head.ref }} \
            --base master \
            --title "${{ github.event.pull_request.title }}" \
            --body "**Replicação automática da PR aprovada em QA**%0A%0APR original: ${{ github.event.pull_request.html_url }}%0AAprovada por: ${{ github.event.review.user.login }}%0AData de aprovação: ${{ github.event.review.submitted_at }}%0A%0A${{ github.event.pull_request.body }}"
        env:
          GH_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
