name: Replicar PR para Produção

# Este workflow requer um PAT (Personal Access Token) clássico com escopo 'repo'
# IMPORTANTE: Use um PAT clássico (não Fine-grained) para autenticação Git
# Armazene o token nos secrets do repositório como API_TOKEN_GITHUB
# Veja: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write

jobs:
  replicar-para-prod:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório de QA
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Pega o histórico completo
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Adicionar repositório de produção como remoto e fazer push
        run: |
          # Usar username + token no formato correto
          git remote add prod https://brunolopesdev:${{ secrets.API_TOKEN_GITHUB }}@github.com/brunolopesdev/nuxt-crud.git

          # Verificar se o remoto foi adicionado corretamente
          git remote -v

          # Fazer push com verbosidade para debug
          git push -v prod ${{ github.event.pull_request.head.ref }}:${{ github.event.pull_request.head.ref }}

      - name: Criar PR usando API direta
        env:
          TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="**Replicação automática da PR aprovada em QA**

          PR original: ${{ github.event.pull_request.html_url }}
          Aprovada por: ${{ github.event.review.user.login }}
          Data de aprovação: ${{ github.event.review.submitted_at }}

          ${{ github.event.pull_request.body }}"

          # Criar PR usando curl e API REST do GitHub
          curl -X POST \
            -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/brunolopesdev/nuxt-crud/pulls \
            -d '{
              "title": "'"$PR_TITLE"'",
              "body": "'"$PR_BODY"'",
              "head": "'"${{ github.event.pull_request.head.ref }}"'",
              "base": "master"
            }'
