name: Replicar PR para Produção

on:
  pull_request_review:
    types: [submitted]

jobs:
  replicar-para-prod:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Criar PR no repositório de produção
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.event.pull_request.head.ref }}
          destination_repository: "brunolopesdev/nuxt-crud"
          destination_branch: "master"
          pr_title: "${{ github.event.pull_request.title }}"
          pr_body: |
            **Replicação automática da PR aprovada em QA**

            PR original: ${{ github.event.pull_request.html_url }}
            Aprovada por: ${{ github.event.review.user.login }}
            Data de aprovação: ${{ github.event.review.submitted_at }}

            ${{ github.event.pull_request.body }}
          pr_reviewer: "tech-lead,product-owner"
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
